import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Navbar, SelectedPartners } from '@/components/atoms'
import {
  About,
  CompareLoans,
  FaqLoans,
  Reviews,
  StepsPersonalLoan
} from '@/components/molecules'
// import { Navbar } from './Components/atoms'
// import CompareLoans from './Components/molecules/CompareLoans'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex flex-col w-full h-full pt-[60px] max-w-[1024px] mx-auto">
        <CompareLoans />
        <SelectedPartners />
      </div>
      <Reviews />
      <StepsPersonalLoan />
      <About />
      <FaqLoans />
    </>
  )
}
